# Generated by Django 3.0.7 on 2020-06-19 07:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20200618_1425'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='Post',
            new_name='post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='Active',
        ),
    ]
