# Generated by Django 3.0.7 on 2020-06-19 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200619_1230'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_created']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='Post',
        ),
        migrations.AddField(
            model_name='comment',
            name='Active',
            field=models.BooleanField(default=True),
        ),
    ]
