# Generated by Django 3.0.7 on 2020-06-20 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='reply',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
